# Generated by Django 5.0.6 on 2024-09-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_on',
        ),
    ]
